const sidebars = {
    worldsSidebar: [
        'intro',
        {
            type: 'category',
            label: '🌿 World 1 — Green Plains',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-1' }],
        },
        {
            type: 'category',
            label: '🕳️ World 2 — Underground',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-2' }],
        },
        {
            type: 'category',
            label: '☁️ World 3 — Sky World',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-3' }],
        },
        {
            type: 'category',
            label: '🌊 World 4 — Water World',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-4' }],
        },
        {
            type: 'category',
            label: '🏰 World 5 — Bowser Castle 1',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-5' }],
        },
        {
            type: 'category',
            label: '🔥 World 6 — Bowser Castle 2',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-6' }],
        },
        {
            type: 'category',
            label: '⭐ World 7 — Star World',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-7' }],
        },
        {
            type: 'category',
            label: '👑 World 8 — Final Castle',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'world-8' }],
        },
        'brand-guide',
    ],
};
export default sidebars;
